# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Or the version you updated to with 'autoupdate'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit # <--- CHANGE THIS BACK TO THIS URL!
    rev: v0.4.8 # Or the latest stable version from astral-sh/ruff-pre-commit releases
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]

  - repo: https://github.com/nbQA-dev/nbQA # This should already be correct from last time
    rev: 1.8.1 # Or the latest stable version
    hooks:
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]
      # - id: nbqa-black
      #   args: [--check]