# .github/workflows/lint_and_format.yaml

name: Code Quality Checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types: [opened, synchronize, reopened]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install pre-commit framework
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        env:
          # --- ADD THESE LINES ---
          # Provide the GitHub token for authentication when pre-commit fetches repositories
          # This is crucial for pre-commit to clone/fetch hook repositories from GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # --- END ADDITION ---
